version: "3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kosmed
    ports:
      - "3306:3306"
